### ISSUE TITLE
Publish the image to the Docker hub registry

### ISSUE THREAD

**Issue by evstmihail** [tijjjy/Tailscale-DERP-Docker#2]
Hi,

It would be nice to see the image in the docker hub registry. Is this possible?

Best regards,
Mike.

**Comment by tijjjy** [comment]
Hi,

Thanks for raising the issue, at your request I have built the container and pushed it to the GitHub container registry.

You can use the following command to pull the container
```
docker pull ghcr.io/tijjjy/tailscale-derp-docker:latest
```

Additionally, using the docker-compose.yml file, simply change this line
```
image: tailscale-derp-docker:1.0
```
To the following
```
ghcr.io/tijjjy/tailscale-derp-docker:latest
```

I hope this helps! Any other issues, please let me know!
