### ISSUE TITLE
Update to the latest tailscale version

### ISSUE THREAD

**Issue by rytekHL** [tijjjy/Tailscale-DERP-Docker#6]
Hi,

Is there a chance to update the image to the latest tailscale version?
It's been built on the 1.58.2 while v1.68.2 is now available.

Thank you in advance.

Regards
Artur.

**Comment by tijjjy** [comment]
Hi, I've updated the container to match the latest version available on [alpine edge](https://pkgs.alpinelinux.org/package/edge/community/x86/tailscale). I've also added a Github actions workflow so it will update every 10 days.
